version: '3'
services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: joomla
      MYSQL_USER: joomla
      MYSQL_PASSWORD: 12345678
    volumes:
      - joomla-db:/var/lib/mysql
  web:
    image: joomla
    links:
      - db
    ports:
      - 80:80
    environment:
     - JOOMLA_DB_HOST=db:3306
     - JOOMLA_DB_PASSWORD=12345678
    volumes:
      - joomla-web:/var/www/html
  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: 12345678
    ports:
      - 8080:80
volumes:
  joomla-db:
  joomla-web:
